# This is a basic workflow to help you get started with Actions

name: Main Branch CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.PRODUCTION_GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.PRODUCTION_GCP_SA_KEY }}
          project_id: ${{ secrets.PRODUCTION_PROJECT_ID }}
          gae_variables: ${{ secrets.GAE_VARIABLES_PRODUCTION }}

      - name: Publish app to Google App Engine
        run: |
          # This client-secret.json is converted by PRODUCTION_GCP_SA_KEY.
          gcloud auth activate-service-account ${{ secrets.PRODUCTION_GCP_SA_EMAIL }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.PRODUCTION_PROJECT_ID }}
          gcloud -q app deploy app.yaml --promote
          # Suppose you need a cron task.
          # gcloud -q app deploy cron.yaml
